import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tr' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  tr: {
    settingsTitle: 'Ayarlar & Daha Fazla',
    settingsSubtitle: 'Uygulamayı kişiselleştirin ve destek alın',
    general: 'Genel',
    language: 'Dil',
    turkish: 'Türkçe',
    english: 'English',
    notifications: 'Bildirimler',
    darkMode: 'Karanlık Mod',
    support: 'Destek',
    helpCenter: 'Yardım Merkezi',
    aboutUs: 'Hakkımızda',
    contact: 'İletişim',
    privacy: 'Gizlilik',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfUse: 'Kullanım Koşulları',
    logOut: 'Çıkış Yap',
    version: 'DermaGlow v1.0.0',
    copyright: '© 2026 DermaGlow. Tüm hakları saklıdır.',
    selectLanguage: 'Dil Seçin',
    helpCenterTitle: 'Yardım Merkezi',
    helpCenterContent: 'Sık sorulan sorular ve kullanım kılavuzu burada yer alacaktır.',
    aboutUsTitle: 'Hakkımızda',
    aboutUsContent: 'DermaGlow ile cilt ve saç analizinizi yapın, rutinlerinizi takip edin.',
    contactTitle: 'İletişim',
    contactContent: 'Bize e-posta veya destek formu ile ulaşabilirsiniz.',
    privacyPolicyTitle: 'Gizlilik Politikası',
    privacyPolicyContent: 'Gizlilik politikamız metni burada yer alacaktır.',
    termsTitle: 'Kullanım Koşulları',
    termsContent: 'Kullanım koşulları metni burada yer alacaktır.',
    // Tabs
    tabHome: 'Ana Sayfa',
    tabRoutine: 'Rutin',
    tabCamera: 'Kamera',
    tabChat: 'Chat',
    tabMore: 'Daha Fazla',
    // Home
    hello: 'Merhaba',
    welcome: 'Hoş geldin',
    welcomeUser: 'Hoş geldin, Nisa',
    // Profile
    profileTitle: 'Profil & Ayarlar',
    personalInfo: 'Kişisel Bilgiler',
    nameSurname: 'Ad Soyad',
    email: 'E-posta',
    password: 'Şifre',
    skinProfile: 'Cilt Profili',
    skinType: 'Cilt Tipi',
    sensitivity: 'Hassasiyet Durumu',
    skinProblems: 'Cilt Sorunları',
    addTag: 'Ekle',
    save: 'Kaydet',
    changePhoto: 'Profil fotoğrafını değiştir',
    skinTypeNormal: 'Normal',
    skinTypeDry: 'Kuru',
    skinTypeOily: 'Yağlı',
    skinTypeCombination: 'Karma',
    skinTypeSensitive: 'Hassas',
    sensitivityLow: 'Az Hassas',
    sensitivityMedium: 'Orta Hassas',
    sensitivityHigh: 'Çok Hassas',
    newPost: 'Yeni Gönderi',
    dailyGoals: 'Günlük Hedefler',
    waterTargetMl: 'ml hedef',
    productFind: 'Ürün Bul',
    searchProductPlaceholder: 'Ürün ara...',
    skinDiscover: 'Cilt tipine uygun ürünleri keşfet',
    skinHealthInfo: 'Cilt Sağlığı Bilgileri',
    drySkinReasons: 'Kuru Cilt Nedenleri',
    drySkinSub: 'Yetersiz su tüketimi ve nem eksikliği cildinizi kurutabilir',
    waterEffect: 'Su Tüketiminin Etkisi',
    waterEffectSub: 'Düzenli su içmek cildinizin nem dengesini korur ve parlaklık sağlar',
    routineDiff: 'Sabah & Akşam Rutini Farkı',
    routineDiffSub: 'Sabah rutini koruma, akşam rutini temizleme ve onarım odaklıdır',
    // Routine
    dailyRoutine: 'Günlük Rutin',
    morningRoutine: 'Sabah Rutini',
    eveningRoutine: 'Akşam Rutini',
    completedCount: 'tamamlandı',
    addTaskPlaceholder: 'Yeni görev ekle...',
    addButton: 'Ekle',
    // Camera
    skinAnalysis: 'Cilt Analizi',
    cameraSubtitle: 'Cildinizin ya da saç derinizin fotoğrafını çekin ve gelişiminizi takip edin',
    takePhoto: 'Fotoğraf Çek',
    selectFromGallery: 'Galeriden Fotoğraf Seç',
    analysisHistory: 'Analiz Geçmişi',
    seeAll: 'Tümünü Gör',
    skinAnalysisType: 'Cilt Analizi',
    scalpAnalysisType: 'Saç Derisi Analizi',
    cameraPermissionTitle: 'Kamera İzni',
    cameraPermissionMessage: 'Fotoğraf çekmek için kamera iznine ihtiyacımız var.',
    cameraPreview: 'Kamera Önizleme',
    skinPhotoMode: 'Cilt Fotoğrafı',
    scalpMode: 'Saç Derisi',
    skinTipsTitle: 'Cilt Analizi İpuçları',
    skinTip1: 'Doğal ışık kullanın',
    skinTip2: 'Yüzünüz tam karşıdan görünsün',
    skinTip3: 'Makyajsız çekim yapın',
    scalpTip1: 'Saçı net ayırın',
    scalpTip2: 'Saç derisi görünür olsun',
    scalpTip3: 'Parlak ışık kullanın',
    ok: 'Tamam',
    cancel: 'İptal',
    later: 'Daha Sonra',
    settings: 'Ayarlar',
    // Chat
    searchUsersTopics: 'Kullanıcı veya konu ara...',
    community: 'Topluluk',
    comment: 'Yorum yap',
    messages: 'Mesajlar',
    createPost: 'Gönderi Oluştur',
    addPhoto: 'Fotoğraf Ekle',
    postPlaceholder: 'Ne paylaşmak istersin?',
    sendPost: 'Paylaş',
    // AnalysisDetail
    skinScore: 'Cilt Skoru',
    scalpScore: 'Saç Derisi Skoru',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    aiCommentImproved: 'Son analizden bu yana cilt bariyeriniz güçlenmiş görünüyor.',
    aiCommentDecreased: 'Nem seviyesi düşüş göstermiş olabilir. Rutin gözden geçirilmeli.',
    aiCommentStable: 'Cilt skorunuz stabil. Mevcut rutininize devam edebilirsiniz.',
    analysisDetailTitle: 'Analiz Detayı',
    // ChatDetail
    typeMessage: 'Mesaj yazın...',
    send: 'Gönder',
    assistantWelcome: 'Merhaba! Ben DermaGlow Asistan. Cilt bakım rutinin hakkında bana her şeyi sorabilirsin.',
  },
  en: {
    settingsTitle: 'Settings & More',
    settingsSubtitle: 'Personalize the app and get support',
    general: 'General',
    language: 'Language',
    turkish: 'Türkçe',
    english: 'English',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    support: 'Support',
    helpCenter: 'Help Center',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacy: 'Privacy',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    logOut: 'Log Out',
    version: 'DermaGlow v1.0.0',
    copyright: '© 2026 DermaGlow. All rights reserved.',
    selectLanguage: 'Select Language',
    helpCenterTitle: 'Help Center',
    helpCenterContent: 'FAQ and user guide will be available here.',
    aboutUsTitle: 'About Us',
    aboutUsContent: 'Analyze your skin and scalp, track your routines with DermaGlow.',
    contactTitle: 'Contact',
    contactContent: 'You can reach us via email or support form.',
    privacyPolicyTitle: 'Privacy Policy',
    privacyPolicyContent: 'Our privacy policy text will appear here.',
    termsTitle: 'Terms of Use',
    termsContent: 'Terms of use text will appear here.',
    tabHome: 'Home',
    tabRoutine: 'Routine',
    tabCamera: 'Camera',
    tabChat: 'Chat',
    tabMore: 'More',
    hello: 'Hello',
    welcome: 'Welcome',
    welcomeUser: 'Welcome, Nisa',
    profileTitle: 'Profile & Settings',
    personalInfo: 'Personal Information',
    nameSurname: 'Full Name',
    email: 'Email',
    password: 'Password',
    skinProfile: 'Skin Profile',
    skinType: 'Skin Type',
    sensitivity: 'Sensitivity',
    skinProblems: 'Skin Concerns',
    addTag: 'Add',
    save: 'Save',
    changePhoto: 'Change profile photo',
    skinTypeNormal: 'Normal',
    skinTypeDry: 'Dry',
    skinTypeOily: 'Oily',
    skinTypeCombination: 'Combination',
    skinTypeSensitive: 'Sensitive',
    sensitivityLow: 'Low',
    sensitivityMedium: 'Medium',
    sensitivityHigh: 'High',
    newPost: 'New Post',
    dailyGoals: 'Daily Goals',
    waterTargetMl: 'ml target',
    productFind: 'Find Product',
    searchProductPlaceholder: 'Search product...',
    skinDiscover: 'Discover products for your skin type',
    skinHealthInfo: 'Skin Health Information',
    drySkinReasons: 'Dry Skin Causes',
    drySkinSub: 'Insufficient water intake and lack of moisture can dry your skin',
    waterEffect: 'Effect of Water Consumption',
    waterEffectSub: 'Drinking water regularly maintains your skin\'s moisture balance and radiance',
    routineDiff: 'Morning & Evening Routine Difference',
    routineDiffSub: 'Morning routine is for protection, evening for cleansing and repair',
    dailyRoutine: 'Daily Routine',
    morningRoutine: 'Morning Routine',
    eveningRoutine: 'Evening Routine',
    completedCount: 'completed',
    addTaskPlaceholder: 'Add new task...',
    addButton: 'Add',
    skinAnalysis: 'Skin Analysis',
    cameraSubtitle: 'Take a photo of your skin or scalp and track your progress',
    takePhoto: 'Take Photo',
    selectFromGallery: 'Select from Gallery',
    analysisHistory: 'Analysis History',
    seeAll: 'See All',
    skinAnalysisType: 'Skin Analysis',
    scalpAnalysisType: 'Scalp Analysis',
    cameraPermissionTitle: 'Camera Permission',
    cameraPermissionMessage: 'We need camera access to take photos.',
    cameraPreview: 'Camera Preview',
    skinPhotoMode: 'Skin Photo',
    scalpMode: 'Scalp',
    skinTipsTitle: 'Skin Analysis Tips',
    skinTip1: 'Use natural light',
    skinTip2: 'Face the camera directly',
    skinTip3: 'Take photo without makeup',
    scalpTip1: 'Part hair clearly',
    scalpTip2: 'Keep scalp visible',
    scalpTip3: 'Use bright lighting',
    ok: 'OK',
    cancel: 'Cancel',
    later: 'Later',
    settings: 'Settings',
    searchUsersTopics: 'Search users or topics...',
    community: 'Community',
    comment: 'Comment',
    messages: 'Messages',
    createPost: 'Create Post',
    addPhoto: 'Add Photo',
    postPlaceholder: 'What do you want to share?',
    sendPost: 'Share',
    skinScore: 'Skin Score',
    scalpScore: 'Scalp Score',
    weekly: 'Weekly',
    monthly: 'Monthly',
    aiCommentImproved: 'Your skin barrier appears stronger since the last analysis.',
    aiCommentDecreased: 'Moisture level may have dropped. Consider reviewing your routine.',
    aiCommentStable: 'Your skin score is stable. You can continue your current routine.',
    analysisDetailTitle: 'Analysis Detail',
    typeMessage: 'Type a message...',
    send: 'Send',
    assistantWelcome: 'Hello! I\'m DermaGlow Assistant. Ask me anything about your skincare routine.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
