import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tr' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  tr: {
    settingsTitle: 'Ayarlar & Daha Fazla',
    settingsSubtitle: 'Uygulamayı kişiselleştirin ve destek alın',
    general: 'Genel',
    language: 'Dil',
    turkish: 'Türkçe',
    english: 'English',
    notifications: 'Bildirimler',
    darkMode: 'Karanlık Mod',
    support: 'Destek',
    helpCenter: 'Yardım Merkezi',
    aboutUs: 'Hakkımızda',
    contact: 'İletişim',
    privacy: 'Gizlilik',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfUse: 'Kullanım Koşulları',
    logOut: 'Çıkış Yap',
    version: 'DermaGlow v1.0.0',
    copyright: '© 2026 DermaGlow. Tüm hakları saklıdır.',
    selectLanguage: 'Dil Seçin',
    helpCenterTitle: 'Yardım Merkezi',
    helpCenterContent:
      'DermaGlow Yardım Merkezi\'ne hoş geldiniz.\n\nBurada uygulamayı nasıl kullanacağınız, analiz ekranlarının ne anlama geldiği ve sık karşılaşılan sorunlar hakkında özet bilgiler bulabilirsiniz.\n\nSık sorulan sorular:\n• Cilt analizi nasıl yapılır?\n  - Ana ekrandan Kamera sekmesine geçin, "Cilt Analizi" modunu seçin ve yönergeleri takip edin.\n• Rutinime nasıl görev eklerim?\n  - Rutin sekmesine gidip "Yeni görev ekle" alanına adını yazın ve Kaydet\'e dokunun.\n• Son analizlerimi nereden görebilirim?\n  - Kamera sekmesindeki "Analiz Geçmişi" bölümünden ulaşabilirsiniz.\n\nDaha detaylı destek için İletişim ekranından bize ulaşabilirsiniz.',
    aboutUsTitle: 'Hakkımızda',
    aboutUsContent:
      'DermaGlow, cilt ve saç derisi sağlığınızı daha bilinçli takip edebilmeniz için tasarlanmış bir kişisel bakım asistanıdır.\n\nAmacımız, karmaşık dermatoloji terimlerini sadeleştirerek herkes için anlaşılır hale getirmek ve günlük bakım rutinlerinizi sürdürülebilir bir alışkanlığa dönüştürmektir.\n\nDermaGlow ile:\n• Cilt ve saç derisi analizi yapabilir,\n• Günlük bakım rutininizi planlayabilir,\n• Zaman içindeki gelişiminizi takip edebilirsiniz.\n\nUygulama, tıbbi tanı koymaz ve doktor muayenesinin yerini almaz. Her zaman cilt sağlığınızla ilgili önemli kararlar için bir uzmana danışmanızı öneririz.',
    contactTitle: 'İletişim',
    contactContent:
      'Her türlü soru, öneri veya geri bildiriminiz bizim için çok değerli.\n\nBize ulaşabileceğiniz kanallar:\n• E-posta: destek@dermaglow.app\n• Geri bildirim: Uygulama içi değerlendirme ve yorum alanları üzerinden uygulama deneyiminizi paylaşabilirsiniz.\n\nGeri dönüş süremiz genellikle 2–3 iş günüdür. Yoğunluk durumuna göre bu süre değişiklik gösterebilir. Size daha iyi bir DermaGlow deneyimi sunabilmemiz için düşüncelerinizi bizimle paylaşmaktan çekinmeyin.',
    privacyPolicyTitle: 'Gizlilik Politikası',
    privacyPolicyContent:
      'Bu gizlilik politikası, DermaGlow uygulamasını kullanırken kişisel verilerinizin nasıl işlendiğini açıklar.\n\nTopladığımız veriler:\n• Profil bilgileri (ad, e-posta, temel cilt profili alanları)\n• Uygulama içi kullanım verileri (hangi ekranların ne sıklıkla kullanıldığı gibi anonim istatistikler)\n\nVerileri nasıl kullanıyoruz?\n• Uygulama deneyimini kişiselleştirmek,\n• Hata ve performans problemlerini tespit etmek,\n• Yeni özellikleri planlamak ve iyileştirmek için.\n\nVeri güvenliği:\n• Verileriniz makul güvenlik önlemleri ile korunur.\n• Verilerinizi üçüncü taraflara satmayız.\n\nHaklarınız:\n• Hesabınızı silmek,\n• Verilerinizin işlenmesine dair bilgi talep etmek için bizimle İletişim ekranı üzerinden bağlantıya geçebilirsiniz.\n\nBu metin bilgilendirme amaçlıdır ve zaman zaman güncellenebilir.',
    termsTitle: 'Kullanım Koşulları',
    termsContent:
      'DermaGlow uygulamasını kullanarak aşağıdaki temel kullanım koşullarını kabul etmiş olursunuz.\n\n1. Hizmetin niteliği\nDermaGlow, kişisel bakım takibi ve bilgilendirme amacıyla tasarlanmış bir mobil uygulamadır. Tıbbi tanı koymaz ve doktor tavsiyesinin yerine geçmez.\n\n2. Sorumluluk reddi\nUygulama içerisindeki öneriler genel bilgilendirme amaçlıdır. Cilt problemleriniz için daima bir dermatolog veya sağlık profesyoneline danışmalısınız.\n\n3. Kullanıcı yükümlülükleri\n• Hesap bilgilerinizin gizliliğinden siz sorumlusunuz.\n• Uygulamayı mevzuata aykırı veya kötüye kullanım amaçlı kullanamazsınız.\n\n4. Değişiklikler\nKullanım koşulları zaman zaman güncellenebilir. Önemli değişiklikler olduğunda uygulama içinden sizi bilgilendirmeye çalışırız.\n\nUygulamayı kullanmaya devam etmeniz, güncel koşulları kabul ettiğiniz anlamına gelir.',
    tabHome: 'Ana Sayfa',
    tabRoutine: 'Rutin',
    tabCamera: 'Kamera',
    tabChat: 'Chat',
    tabMore: 'Daha Fazla',
    hello: 'Merhaba',
    welcome: 'Hoş geldin',
    welcomeUser: 'Hoş geldin, Nisa',
    profileTitle: 'Profil & Ayarlar',
    personalInfo: 'Kişisel Bilgiler',
    nameSurname: 'Ad Soyad',
    email: 'E-posta',
    password: 'Şifre',
    skinProfile: 'Cilt Profili',
    skinType: 'Cilt Tipi',
    sensitivity: 'Hassasiyet Durumu',
    skinProblems: 'Cilt Sorunları',
    birthDate: 'Doğum tarihi',
    height: 'Boy (cm)',
    weight: 'Kilo (kg)',
    addTag: 'Ekle',
    save: 'Kaydet',
    changePhoto: 'Profil fotoğrafını değiştir',
    skinTypeNormal: 'Normal',
    skinTypeDry: 'Kuru',
    skinTypeOily: 'Yağlı',
    skinTypeCombination: 'Karma',
    skinTypeSensitive: 'Hassas',
    sensitivityLow: 'Az Hassas',
    sensitivityMedium: 'Orta Hassas',
    sensitivityHigh: 'Çok Hassas',
    newPost: 'Yeni Gönderi',
    dailyGoals: 'Günlük Hedefler',
    waterTargetMl: 'ml hedef',
    addWater: 'Su ekle',
    add200ml: '+200 ml',
    add500ml: '+500 ml',
    customMlPlaceholder: 'Özel miktar (ml)',
    customAmountLabel: 'Özel miktar',
    addWaterButton: 'Ekle',
    undoWater: 'Geri al',
    waterCelebrationTitle: 'Tebrikler! 🎉',
    waterCelebrationMessage: 'Günlük su hedefinize ulaştınız!',
    productFind: 'Ürün Bul',
    searchProductPlaceholder: 'Ürün ara...',
    skinDiscover: 'Cilt tipine uygun ürünleri keşfet',
    productSearchInfo:
      'Ürün adını yazabilir, barkod ile hızlıca okutabilir veya aşağıdaki filtreleri kullanarak cilt tipine uygun ürünleri keşfedebilirsin.',
    scanBarcodeButton: 'Barkod Tara',
    scanBarcodeTooltip: 'Barkod okutmak için dokun',
    manualBarcodePlaceholder: 'Barkod no yazın',
    barcodeSearchButton: 'Ara',
    scannedCodeLabel: 'Okutulan barkod',
    filtersTitle: 'Filtreler',
    filterCleanser: 'Temizleyici (Jel, Köpük, Yağ bazlı)',
    filterToner: 'Tonik',
    filterSerum: 'Serum',
    filterMoisturizer: 'Nemlendirici',
    filterSunscreen: 'Güneş Kremi',
    filterExfoliant: 'Peeling / Eksfoliant',
    filterMask: 'Maske',
    filterEyeCare: 'Göz Çevresi Bakımı',
    filterLipCare: 'Dudak Bakımı',
    filterAcne: 'Akne Tedavi Ürünleri',
    filterHairMask: 'Saç Maskesi',
    filterOther: 'Diğer',
    skinHealthInfo: 'Cilt Sağlığı Bilgileri',
    drySkinReasons: 'Kuru Cilt Nedenleri',
    drySkinSub: 'Kuru cilt genellikle yetersiz su tüketimi ve nem eksikliği nedeniyle oluşur. Soğuk hava ve yanlış cilt bakımı da etkiler.',
    drySkinDetail:
      'Kuru cilt, cilt bariyerinin zayıflaması ve nem tutma kapasitesinin azalmasıyla ortaya çıkar.\n\nBaşlıca nedenler:\n• Yetersiz su tüketimi ve düşük nem oranı\n• Sert temizleyiciler ve alkol içeriği yüksek tonikler\n• Soğuk, rüzgarlı hava ve ani sıcaklık değişimleri\n• Yetersiz nemlendirici kullanımı veya cilt tipine uygun olmayan ürünler\n\nNe yapabilirsin?\n• Gün içinde düzenli su tüketmeye özen göster.\n• Cildini nazik, krem veya jel formda temizleyicilerle temizle.\n• Duş sonrası ilk 3–5 dakika içinde nemlendiricini uygula.\n• Kış aylarında daha yoğun dokulu, bariyer güçlendirici kremler tercih et.',
    waterEffect: 'Su Tüketiminin Etkisi',
    waterEffectSub: 'Düzenli su içmek cildin nem dengesini korur, elastikiyetini artırır ve sağlıklı bir parlaklık sağlar.',
    waterEffectDetail:
      'Vücudunun büyük bir kısmı sudan oluşur ve cilt, bu su dengesinden doğrudan etkilenir.\n\nDüzenli su tüketimi:\n• Cildin nem dengesini içeriden destekler,\n• Elastikiyetin korunmasına yardımcı olur,\n• Mat ve yorgun görünümü azaltabilir,\n• Toksinlerin atılım sürecini destekleyerek daha canlı bir görünüm sağlayabilir.\n\nKüçük ipuçları:\n• Gün içine yayılmış şekilde su içmeye çalış (örneğin her saat birkaç yudum).\n• Suyu sade içmek zor geliyorsa limon dilimi veya meyve parçalarıyla tatlandırabilirsin.\n• Kafeinli içecekleri aşırıya kaçmadan tüketmeye özen göster; çünkü vücuttan su atılımını artırabilirler.',
    routineDiff: 'Sabah & Akşam Rutini Farkı',
    routineDiffSub: 'Sabah rutini cildi korumaya, akşam rutini ise temizlemeye ve onarmaya odaklanır. Her ikisi de cilt sağlığı için önemlidir.',
    routineDiffDetail:
      'Sabah ve akşam rutinleri aynı ürünlerden oluşsa bile amaçları farklıdır.\n\nSabah rutini odağı:\n• Gece boyunca biriken fazla sebumu nazikçe arındırmak,\n• Cildi güne hazırlamak ve çevresel faktörlere (güneş, kirlilik vb.) karşı korumak,\n• Güneş koruyucu ile cilt bariyerini desteklemek.\n\nAkşam rutini odağı:\n• Makyaj, güneş kremi ve gün boyu biriken kirleri tamamen temizlemek,\n• Cilt bariyerini onarmaya yardımcı aktif içerikleri (nemlendiriciler, bariyer destekleyiciler vb.) uygulamak,\n• Hücre yenilenmesinin en aktif olduğu gece saatlerinde cilde bakım yapmak.\n\nİpucu: Rutinini cilt tipine ve mevsime göre hafifçe güncellemek, uzun vadede daha dengeli bir cilt görünümü sağlar.',
    onb_header_small: 'Seni daha yakından tanıyalım',
    onb_header_title: 'Cildinle ilgili birkaç soru 🤍',
    onb_skip: 'Sonra doldur',
    onb_back: 'Geri',
    onb_next: 'Devam',
    onb_finish: 'Bitir',
    onb_yes: 'Evet',
    onb_no: 'Hayır',
    onb_sometimes: 'Bazen',
    onb_opt_unsure: 'Emin değilim',
    onb_q1_title: 'Biyolojik cinsiyetiniz nedir?',
    onb_q1_opt1: 'Kadın',
    onb_q1_opt2: 'Erkek',
    onb_q1_opt3: 'Belirtmek istemiyorum',
    onb_q2_title: 'Doğum tarihiniz nedir?',
    onb_q2_desc: 'Yaşınızı doğru değerlendirebilmek için gün/ay/yıl şeklinde seçin.',
    onb_q2_placeholder: 'Gün / Ay / Yıl seçmek için dokunun',
    onb_q2_selected: 'Tarih seçildi',
    onb_q3_title: 'Cildini genellikle nasıl hissediyorsun?',
    onb_q3_opt1: 'Kuru ve gergin',
    onb_q3_opt2: 'Yağlı ve parlak',
    onb_q3_opt3: 'Karma (T bölgesi yağlı)',
    onb_q3_opt4: 'Normal / Dengeli',
    onb_q4_title: 'Gün içinde yüzünüz ne kadar yağlanır?',
    onb_q4_opt1: 'Hiç',
    onb_q4_opt2: 'Hafif',
    onb_q4_opt3: 'Belirgin',
    onb_q4_opt4: 'Çok fazla',
    onb_q5_title: 'Duş sonrasında cildinizde gerginlik oluyor mu?',
    onb_q6_title: 'Aşağıdaki cilt problemlerinden hangilerini yaşıyorsunuz?',
    onb_q6_opt1: 'Akne / sivilce',
    onb_q6_opt2: 'Siyah nokta',
    onb_q6_opt3: 'Leke',
    onb_q6_opt4: 'Kızarıklık',
    onb_q6_opt5: 'Kırışıklık',
    onb_q6_opt6: 'Gözenek görünümü',
    onb_q7_title: 'Cilt hassasiyetiniz var mı?',
    onb_q7_opt1: 'Evet, kolay kızarır',
    onb_q7_opt2: 'Bazen hassaslaşıyor',
    onb_q7_opt3: 'Hayır, hassas değil',
    onb_q8_title: 'Güneş kremi kullanıyor musunuz?',
    onb_yes_daily: 'Evet, her gün',
    onb_yes_sometimes: 'Bazen kullanıyorum',
    onb_q9_title: 'Günlük su tüketiminiz yaklaşık ne kadar?',
    onb_q9_opt1: '1 litreden az',
    onb_q9_opt2: '1–2 litre',
    onb_q9_opt3: '2 litreden fazla',
    onb_q10_title: 'Makyaj yapıyor musunuz?',
    onb_q10_opt1: 'Her gün',
    onb_q10_opt2: 'Ara sıra',
    onb_q10_opt3: 'Hiç yapmıyorum',
    onb_q11_title: 'Yanak bölgeni en iyi hangi meyve tanımlar?',
    onb_q11_opt1: '🍎 Elma gibi pürüzsüz',
    onb_q11_opt2: '🍋 Limon gibi pürüzlü ve gözenekli',
    onb_q11_opt3: '🍊 Portakal gibi pürüzlü',
    onb_q11_opt4: '🍓 Çilek gibi dolgun',
    onb_q11_opt5: '🍑 Şeftali gibi yumuşak',
    onb_q12_title: 'Yüzüne yakından baktığında nerelerde çizgi görüyorsun?',
    onb_q12_opt1: 'Göz çevresinde',
    onb_q12_opt2: 'Ağız çevresinde',
    onb_q12_opt3: 'Alın bölgesinde',
    onb_q12_opt4: 'Her yerde',
    onb_q12_opt5: 'Hiçbir yerde',
    onb_q13_title: 'Cilt bakımından en büyük beklentiniz ne?',
    onb_q13_opt1: 'Sivilce / akne azalması',
    onb_q13_opt2: 'Leke görünümünü azaltmak',
    onb_q13_opt3: 'Daha parlak ve canlı görünüm',
    onb_q13_opt4: 'Yaşlanma karşıtı bakım',
    onb_q13_opt5: 'Nem dengesini sağlamak',
    onb_q14_title: 'Cilt renginizi nasıl tanımlarsınız?',
    onb_q14_opt1: 'Çok açık',
    onb_q14_opt2: 'Açık',
    onb_q14_opt3: 'Orta',
    onb_q14_opt4: 'Buğday / esmer',
    onb_q14_opt5: 'Koyu ten',
    onb_q15_title: 'Herhangi bir dermatolojik tedavi görüyor musunuz?',
    onb_q16_title: 'Reçeteli cilt ürünü kullanıyor musunuz?',
    onb_q17_title: 'Hamilelik veya hormonal bir tedavi süreciniz var mı?',
    onb_q18_title: 'Cilt bakımına ayırabileceğiniz süre ne kadar?',
    onb_q18_opt1: 'Yaklaşık 5 dakika',
    onb_q18_opt2: 'Yaklaşık 10 dakika',
    onb_q18_opt3: '20 dakika ve üzeri',
    onb_q19_title: 'Cildinde geçmişte sivilce bulunan yerler daha koyu görünüyor mu?',
    onb_q20_title: 'Yüzünüzde çok fazla siyah nokta var mı?',
    onb_month_1: 'Ocak',
    onb_month_2: 'Şubat',
    onb_month_3: 'Mart',
    onb_month_4: 'Nisan',
    onb_month_5: 'Mayıs',
    onb_month_6: 'Haziran',
    onb_month_7: 'Temmuz',
    onb_month_8: 'Ağustos',
    onb_month_9: 'Eylül',
    onb_month_10: 'Ekim',
    onb_month_11: 'Kasım',
    onb_month_12: 'Aralık',
    onb_result_title: 'Cilt analizin hazır',
    onb_result_sub:
      'Bu özet tıbbi bir tanı değildir; seni daha iyi tanımak ve bakım önerilerini buna göre uyarlamak için hazırlanmıştır.',
    onb_result_skin_title: 'Genel cilt yapın 🌸',
    onb_result_skin_dry:
      'Yanıtlarına göre cilt yapın kurumaya yatkın görünüyor. Nazik temizleyiciler, bariyer güçlendirici nemlendiriciler ve düzenli su tüketimi senin için özellikle önemli.',
    onb_result_skin_oily:
      'Cildin yağlanmaya eğilimli. Köpüren ama kurutmayan temizleyiciler, hafif yapılı nemlendiriciler ve düzenli güneş koruyucu kullanımı denge sağlamana yardımcı olabilir.',
    onb_result_skin_combo:
      'Cildin T bölgesi daha yağlı, yanaklar ise daha dengeli veya kuru olabilir. Bölgesel bakım (T bölgesine daha hafif, yanaklara daha nemli ürünler) senin için ideal olabilir.',
    onb_result_skin_normal:
      'Cildin genel olarak dengeli görünüyor. Bariyerini koruyan nazik ürünler ve düzenli güneş koruması ile bu dengeyi sürdürebilirsin.',
    onb_result_hydration_title: 'Nem ve su dengesi 💧',
    onb_result_hydration_low:
      'Su tüketimin düşük görünüyor. Gün içine yayılmış küçük yudumlar, hem genel sağlığın hem de cilt nem dengen için iyi bir başlangıç olur.',
    onb_result_hydration_mid:
      'Su tüketimin fena değil, ancak cilt kuruluğu hissediyorsan miktarı veya gün içine yayılışını gözden geçirmek faydalı olabilir.',
    onb_result_hydration_good:
      'Su tüketimin gayet iyi görünüyor. Bunu, cildinin dışarıdan nemlendirilmesiyle birleştirmen, daha aydınlık ve dolgun bir görünüm sağlayabilir.',
    onb_result_sun_title: 'Güneş koruması ☀️',
    onb_result_sun_good:
      'Güneş kremini düzenli kullanıyor olman cilt yaşlanmasını yavaşlatmak ve leke riskini azaltmak için harika bir adım. Bu alışkanlığı mutlaka korumalısın.',
    onb_result_sun_mid:
      'Zaman zaman güneş kremi kullanıyorsun; bu iyi bir başlangıç. Her gün, özellikle gündüz bakım rutininin son adımı olarak kullanmak cildini daha iyi korur.',
    onb_result_sun_low:
      'Güneş kremi kullanmıyorsun veya çok nadir kullanıyorsun. UV ışınları leke, ince çizgi ve hassasiyeti artırabilir; günlük bir SPF eklemek uzun vadede büyük fark yaratır.',
    onb_result_focus_title: 'Bakım odağın ✨',
    onb_result_focus_text_prefix: 'Bu rutinde özellikle şu hedefe odaklanacağız: ',
    onb_result_cta: 'Uygulamaya Başla',
    dailyRoutine: 'Günlük Rutin',
    morningRoutine: 'Sabah Rutini',
    eveningRoutine: 'Akşam Rutini',
    completedCount: 'tamamlandı',
    addTaskPlaceholder: 'Yeni görev ekle...',
    addButton: 'Ekle',
    customTimeLabel: 'Özel',
    tapToSetTime: 'Saat için dokun',
    setTime: 'Saat seç',
    skinAnalysis: 'Cilt Analizi',
    cameraSubtitle: 'Cildinizin ya da saç derinizin fotoğrafını çekin ve gelişiminizi takip edin',
    takePhoto: 'Fotoğraf Çek',
    selectFromGallery: 'Galeriden Fotoğraf Seç',
    analysisHistory: 'Analiz Geçmişi',
    seeAll: 'Tümünü Gör',
    skinAnalysisType: 'Cilt Analizi',
    scalpAnalysisType: 'Saç Derisi Analizi',
    cameraPermissionTitle: 'Kamera İzni',
    cameraPermissionMessage: 'Fotoğraf çekmek için kamera iznine ihtiyacımız var.',
    cameraPreview: 'Kamera Önizleme',
    skinPhotoMode: 'Cilt Fotoğrafı',
    scalpMode: 'Saç Derisi',
    skinTipsTitle: 'Cilt Analizi İpuçları',
    skinTip1: 'Doğal ışık kullanın',
    skinTip2: 'Yüzünüz tam karşıdan görünsün',
    skinTip3: 'Makyajsız çekim yapın',
    scalpTip1: 'Saçı net ayırın',
    scalpTip2: 'Saç derisi görünür olsun',
    scalpTip3: 'Parlak ışık kullanın',
    skinGuidance: 'Yüzünüzü çerçevenin ortasına yerleştirin',
    scalpGuidance: 'Saç ayrımını çerçevenin ortasına getirin',
    ok: 'Tamam',
    cancel: 'İptal',
    later: 'Daha Sonra',
    settings: 'Ayarlar',
    searchUsersTopics: 'Kullanıcı veya konu ara...',
    community: 'Topluluk',
    comment: 'Yorum yap',
    messages: 'Mesajlar',
    createPost: 'Gönderi Oluştur',
    addPhoto: 'Fotoğraf Ekle',
    postPlaceholder: 'Ne paylaşmak istersin?',
    sendPost: 'Paylaş',
    skinScore: 'Cilt Skoru',
    scalpScore: 'Saç Derisi Skoru',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    aiCommentImproved: 'Son analizden bu yana cilt bariyeriniz güçlenmiş görünüyor.',
    aiCommentDecreased: 'Nem seviyesi düşüş göstermiş olabilir. Rutin gözden geçirilmeli.',
    aiCommentStable: 'Cilt skorunuz stabil. Mevcut rutininize devam edebilirsiniz.',
    analysisDetailTitle: 'Analiz Detayı',
    typeMessage: 'Mesaj yazın...',
    send: 'Gönder',
    assistantWelcome: 'Merhaba! Ben DermAI. Cilt bakım rutinin hakkında bana her şeyi sorabilirsin.',
    loginTab: 'Giriş Yap',
    signUpTab: 'Kayıt Ol',
    namePlaceholder: 'Ad',
    surnamePlaceholder: 'Soyad',
    emailPlaceholder: 'E-posta',
    passwordPlaceholder: 'Şifre',
    confirmPasswordPlaceholder: 'Şifreyi tekrarla',
    forgotPassword: 'Şifremi unuttum',
    loginButton: 'Giriş Yap',
    signUpButton: 'Kayıt Ol',
    appName: 'DermaGlow',
    resetPasswordTitle: 'Yeni Şifre Oluştur',
    resetPasswordSubtitle: 'Hesabınız için yeni bir şifre belirleyin.',
    newPasswordPlaceholder: 'Yeni şifre',
    confirmNewPasswordPlaceholder: 'Yeni şifreyi tekrarla',
    updatePasswordButton: 'Şifreyi Güncelle',
    resetPasswordSuccess: 'Şifreniz güncellendi. Giriş yapabilirsiniz.',
    resetPasswordErrorShort: 'Şifre en az 6 karakter olmalıdır.',
    resetPasswordErrorMismatch: 'Şifreler eşleşmiyor.',
    resetPasswordUseEmailLink: 'Şifre sıfırlama linkine e-postanızdan ulaşın. Link ile bu sayfaya geldiğinizde yeni şifrenizi girebilirsiniz.',
    errorTitle: 'Hata',
    successTitle: 'Başarılı',
    fillAllFields: 'Lütfen tüm alanları doldurun.',
    passwordsNotMatch: 'Şifreler eşleşmiyor.',
    enterEmailPassword: 'Lütfen e-posta ve şifrenizi girin.',
    enterEmailFirst: 'Şifrenizi sıfırlamak için lütfen önce e-posta adresinizi girin.',
    resetMailSent: 'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
    accountCreated: 'Hesabınız başarıyla oluşturuldu. Şimdi cildinizi daha yakından tanıyalım.',

    // Premium UI
    welcomeTagline: 'Cildiniz için kişisel bakım asistanı',
    welcomeSubtitle: 'AI destekli analiz, özel rutinler ve topluluk önerileriyle cildinizi keşfedin.',
    welcomeFooter: 'Devam ederek Kullanım Koşulları ve Gizlilik Politikasını kabul etmiş olursunuz.',
    signInButton: 'Giriş Yap',
    loginSubtitle: 'Hesabınıza giriş yapın',
    noAccountYet: 'Hesabınız yok mu?',
    createAccountTitle: 'Hesap Oluştur',
    createAccountSubtitle: 'DermaGlow ailesine katılın',
    fullNamePlaceholder: 'Ad Soyad',
    createAccountButton: 'Hesap Oluştur',
    haveAccountAlready: 'Zaten hesabınız var mı?',
    loginInstead: 'Giriş Yap',
    forgotPasswordTitle: 'Şifremi Unuttum',
    forgotPasswordSubtitle: 'E-posta adresinize şifre sıfırlama bağlantısı göndereceğiz.',
    sendResetLink: 'Sıfırlama Bağlantısı Gönder',
    backToLogin: 'Girişe Dön',
    welcomeBack: 'Tekrar hoş geldin',
    skinHealthScore: 'Cilt Sağlık Skoru',
    scalpHealthScore: 'Saç Derisi Skoru',
    recommendedProducts: 'Önerilen Ürünler',
    communityHighlights: 'Topluluk Öne Çıkanlar',
    quickActions: 'Hızlı İşlemler',
    dailyTips: 'Günlük İpuçları',
    upcomingRoutine: 'Yaklaşan Rutin Görevleri',
    scalpAnalysis: 'Saç Derisi Analizi',
    compatibility: 'Uyumluluk',
    rating: 'Puan',
    reviews: 'yorum',
    viewAll: 'Tümünü Gör',
    hydrationTracker: 'Günlük Hidrasyon',
    tabCommunity: 'Topluluk',
    tabPremium: 'Premium',
    tabProfile: 'Profil',
    seeMore: 'Devamını oku',
    emptyRoutine: 'Bugün için bekleyen görev yok',
    tipHydration: 'Günde en az 2L su içmek cilt elastikiyetini destekler.',
    tipSunscreen: 'Her gün SPF 30+ güneş kremi kullanmayı unutmayın.',
    tipRoutine: 'Akşam rutininizi yatmadan 30 dk önce tamamlayın.',

    // Premium
    premiumBadge: 'DermaGlow Premium',
    premiumTitle: 'Premium\'a Yükselt',
    premiumSubtitle: 'Gelişmiş AI analizleri, özel ürün önerileri ve sınırsız rutin takibi.',
    currentPlan: 'Mevcut Plan',
    freePlan: 'Ücretsiz',
    active: 'Aktif',
    premiumFeaturesTitle: 'Premium Özellikler',
    premiumFeature1: 'Sınırsız cilt ve saç derisi AI analizi',
    premiumFeature2: 'Detaylı skor raporları ve trend grafikleri',
    premiumFeature3: 'Kişiselleştirilmiş AI bakım asistanı',
    premiumFeature4: 'Özel ürün önerileri ve topluluk erişimi',
    premiumFeature5: 'Öncelikli müşteri desteği',
    premiumFeature6: 'Reklamsız deneyim',
    premiumPlansTitle: 'Planlar',
    premiumPlanMonthly: 'Aylık Plan',
    premiumPlanYearly: 'Yıllık Plan',
    premiumPriceMonthly: '₺149 / ay',
    premiumPriceYearly: '₺999 / yıl',
    premiumYearlySaving: '%44 tasarruf',
    mostPopular: 'En Popüler',
    upgradeNow: 'Premium\'a Geç',
    premiumDisclaimer: 'Abonelik otomatik yenilenir. İstediğiniz zaman iptal edebilirsiniz.',
    authErrorInvalidCredentials: 'Girdiğiniz e-posta veya şifre hatalı. Lütfen kontrol edin.',
    authErrorAlreadyRegistered: 'Bu e-posta adresi ile zaten kayıt olunmuş.',
  },
  en: {
    settingsTitle: 'Settings & More',
    settingsSubtitle: 'Personalize the app and get support',
    general: 'General',
    language: 'Language',
    turkish: 'Türkçe',
    english: 'English',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    support: 'Support',
    helpCenter: 'Help Center',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacy: 'Privacy',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    logOut: 'Log Out',
    version: 'DermaGlow v1.0.0',
    copyright: '© 2026 DermaGlow. All rights reserved.',
    selectLanguage: 'Select Language',
    helpCenterTitle: 'Help Center',
    helpCenterContent:
      'Welcome to the DermaGlow Help Center.\n\nHere you can find quick explanations on how to use the app, what the analysis screens mean, and answers to common issues.\n\nFrequently asked questions:\n• How do I perform a skin analysis?\n  - Go to the Camera tab on the home screen, choose "Skin Analysis" mode and follow the on‑screen steps.\n• How can I add steps to my routine?\n  - Open the Routine tab, type the name of your task into "Add new task" and tap Add.\n• Where can I see my past analyses?\n  - Check the "Analysis History" section in the Camera tab.\n\nFor more detailed support, you can contact us from the Contact screen.',
    aboutUsTitle: 'About Us',
    aboutUsContent:
      'DermaGlow is a personal care assistant designed to help you track your skin and scalp health more consciously.\n\nOur goal is to simplify complex dermatology concepts so that everyone can understand them, and to turn your daily care routines into sustainable habits.\n\nWith DermaGlow you can:\n• Perform skin and scalp analyses,\n• Plan your daily care routine,\n• Track your progress over time.\n\nDermaGlow does not provide medical diagnosis and is not a substitute for a doctor\'s examination. Always consult a professional for important decisions about your skin health.',
    contactTitle: 'Contact',
    contactContent:
      'Your questions, ideas and feedback are very valuable to us.\n\nYou can reach us via:\n• E‑mail: support@dermaglow.app\n• Feedback: You can share your experience through in‑app ratings and comments.\n\nOur usual response time is 2–3 business days, depending on overall volume. Please do not hesitate to share your thoughts so we can build a better DermaGlow experience for you.',
    privacyPolicyTitle: 'Privacy Policy',
    privacyPolicyContent:
      'This privacy policy explains how your personal data is processed when you use the DermaGlow app.\n\nData we collect:\n• Profile information (name, e‑mail, basic skin profile fields)\n• In‑app usage data (anonymous statistics such as which screens are used and how often)\n\nHow we use this data:\n• To personalize your app experience,\n• To detect errors and performance issues,\n• To plan and improve new features.\n\nData security:\n• Your data is protected with reasonable security measures.\n• We do not sell your data to third parties.\n\nYour rights:\n• Request deletion of your account,\n• Request information about how your data is processed via the Contact screen.\n\nThis text is for information purposes and may be updated from time to time.',
    termsTitle: 'Terms of Use',
    termsContent:
      'By using the DermaGlow app, you agree to the following basic terms of use.\n\n1. Nature of the service\nDermaGlow is a mobile application designed for personal care tracking and general information. It does not provide medical diagnosis and is not a replacement for professional medical advice.\n\n2. Disclaimer\nThe suggestions and explanations in the app are for general information only. Always consult a dermatologist or healthcare professional for skin problems.\n\n3. User obligations\n• You are responsible for keeping your account information confidential.\n• You may not use the app for illegal or abusive purposes.\n\n4. Changes\nThese terms of use may be updated from time to time. We will try to notify you of important changes through the app.\n\nContinuing to use the app means you accept the latest version of these terms.',
    tabHome: 'Home',
    tabRoutine: 'Routine',
    tabCamera: 'Camera',
    tabChat: 'Chat',
    tabMore: 'More',
    hello: 'Hello',
    welcome: 'Welcome',
    welcomeUser: 'Welcome, Nisa',
    profileTitle: 'Profile & Settings',
    personalInfo: 'Personal Information',
    nameSurname: 'Full Name',
    email: 'Email',
    password: 'Password',
    skinProfile: 'Skin Profile',
    skinType: 'Skin Type',
    sensitivity: 'Sensitivity',
    skinProblems: 'Skin Concerns',
    birthDate: 'Date of birth',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    addTag: 'Add',
    save: 'Save',
    changePhoto: 'Change profile photo',
    skinTypeNormal: 'Normal',
    skinTypeDry: 'Dry',
    skinTypeOily: 'Oily',
    skinTypeCombination: 'Combination',
    skinTypeSensitive: 'Sensitive',
    sensitivityLow: 'Low',
    sensitivityMedium: 'Medium',
    sensitivityHigh: 'High',
    newPost: 'New Post',
    dailyGoals: 'Daily Goals',
    waterTargetMl: 'ml target',
    addWater: 'Add water',
    add200ml: '+200 ml',
    add500ml: '+500 ml',
    customMlPlaceholder: 'Custom amount (ml)',
    customAmountLabel: 'Custom amount',
    addWaterButton: 'Add',
    undoWater: 'Undo',
    waterCelebrationTitle: 'Congratulations! 🎉',
    waterCelebrationMessage: 'You\'ve reached your daily water goal!',
    productFind: 'Find Product',
    searchProductPlaceholder: 'Search product...',
    skinDiscover: 'Discover products for your skin type',
    productSearchInfo:
      'Type a product name, scan a barcode, or use the filters below to explore products that match your skin needs.',
    scanBarcodeButton: 'Scan Barcode',
    scanBarcodeTooltip: 'Click to scan a barcode',
    manualBarcodePlaceholder: 'Enter barcode number',
    barcodeSearchButton: 'Search',
    scannedCodeLabel: 'Scanned barcode',
    filtersTitle: 'Filters',
    filterCleanser: 'Cleanser (Gel, Foam, Oil-based)',
    filterToner: 'Toner',
    filterSerum: 'Serum',
    filterMoisturizer: 'Moisturizer',
    filterSunscreen: 'Sunscreen',
    filterExfoliant: 'Peeling / Exfoliant',
    filterMask: 'Mask',
    filterEyeCare: 'Eye Care',
    filterLipCare: 'Lip Care',
    filterAcne: 'Acne Treatment',
    filterHairMask: 'Hair Mask',
    filterOther: 'Other',
    skinHealthInfo: 'Skin Health Information',
    drySkinReasons: 'Dry Skin Causes',
    drySkinSub: 'Insufficient water intake and lack of moisture can dry your skin',
    drySkinDetail:
      'Dry skin appears when the skin barrier weakens and its ability to hold moisture is reduced.\n\nMain causes:\n• Insufficient water intake and low humidity\n• Harsh cleansers and high‑alcohol toners\n• Cold, windy weather and sudden temperature changes\n• Not using enough moisturizer or using products not suited to your skin type\n\nWhat can you do?\n• Try to drink water regularly throughout the day.\n• Cleanse your skin with gentle cream or gel cleansers.\n• Apply your moisturizer within the first 3–5 minutes after showering.\n• In winter, choose richer, barrier‑supporting creams.',
    waterEffect: 'Effect of Water Consumption',
    waterEffectSub: 'Drinking water regularly maintains your skin\'s moisture balance and radiance',
    waterEffectDetail:
      'A large part of your body is made up of water, and your skin is directly affected by this balance.\n\nRegular water intake can:\n• Support the skin\'s moisture balance from within,\n• Help maintain elasticity,\n• Reduce a dull and tired appearance,\n• Support detox processes, contributing to a more radiant look.\n\nSmall tips:\n• Try to sip water throughout the day (for example, a few sips every hour).\n• If plain water is hard to drink, you can flavor it with lemon slices or pieces of fruit.\n• Be mindful with excessive caffeine intake, as it may increase water loss from the body.',
    routineDiff: 'Morning & Evening Routine Difference',
    routineDiffSub: 'Morning routine is for protection, evening for cleansing and repair',
    routineDiffDetail:
      'Even when you use similar products, morning and evening routines have different goals.\n\nMorning routine focus:\n• Gently remove excess sebum that accumulated overnight,\n• Prepare the skin for the day and protect it from environmental factors (sun, pollution, etc.),\n• Support the skin barrier with sunscreen.\n\nEvening routine focus:\n• Thoroughly remove makeup, sunscreen and daily buildup,\n• Apply repairing and barrier‑supporting products (moisturizers, barrier‑strengthening formulas, etc.),\n• Care for the skin during night‑time when cell renewal is most active.\n\nTip: Adjusting your routine slightly based on your skin type and the season can help you maintain a more balanced complexion in the long term.',
    onb_header_small: 'Let us get to know you',
    onb_header_title: 'A few questions about your skin 🤍',
    onb_skip: 'Fill in later',
    onb_back: 'Back',
    onb_next: 'Next',
    onb_finish: 'Finish',
    onb_yes: 'Yes',
    onb_no: 'No',
    onb_sometimes: 'Sometimes',
    onb_opt_unsure: 'Not sure',
    onb_q1_title: 'What is your biological sex?',
    onb_q1_opt1: 'Female',
    onb_q1_opt2: 'Male',
    onb_q1_opt3: 'Prefer not to say',
    onb_q2_title: 'What is your date of birth?',
    onb_q2_desc: 'Select your date of birth in day / month / year format so we can better understand your skin needs.',
    onb_q2_placeholder: 'Tap to choose day / month / year',
    onb_q2_selected: 'Date selected',
    onb_q3_title: 'How does your skin usually feel?',
    onb_q3_opt1: 'Dry and tight',
    onb_q3_opt2: 'Oily and shiny',
    onb_q3_opt3: 'Combination (oily T‑zone)',
    onb_q3_opt4: 'Normal / balanced',
    onb_q4_title: 'How oily does your face get during the day?',
    onb_q4_opt1: 'Not at all',
    onb_q4_opt2: 'Slightly',
    onb_q4_opt3: 'Noticeably',
    onb_q4_opt4: 'Very oily',
    onb_q5_title: 'Does your skin feel tight after showering?',
    onb_q6_title: 'Which of the following skin concerns do you experience?',
    onb_q6_opt1: 'Acne / breakouts',
    onb_q6_opt2: 'Blackheads',
    onb_q6_opt3: 'Dark spots / hyperpigmentation',
    onb_q6_opt4: 'Redness',
    onb_q6_opt5: 'Wrinkles / fine lines',
    onb_q6_opt6: 'Visible pores',
    onb_q7_title: 'Is your skin sensitive?',
    onb_q7_opt1: 'Yes, it easily turns red',
    onb_q7_opt2: 'Sometimes sensitive',
    onb_q7_opt3: 'No, not really',
    onb_q8_title: 'Do you use sunscreen?',
    onb_yes_daily: 'Yes, every day',
    onb_yes_sometimes: 'Sometimes',
    onb_q9_title: 'Approximately how much water do you drink per day?',
    onb_q9_opt1: 'Less than 1 litre',
    onb_q9_opt2: '1–2 litres',
    onb_q9_opt3: 'More than 2 litres',
    onb_q10_title: 'Do you wear makeup?',
    onb_q10_opt1: 'Every day',
    onb_q10_opt2: 'Sometimes',
    onb_q10_opt3: 'Never',
    onb_q11_title: 'Which fruit best describes your cheeks?',
    onb_q11_opt1: '🍎 Smooth like an apple',
    onb_q11_opt2: '🍋 Textured with visible pores like a lemon',
    onb_q11_opt3: '🍊 Rough like an orange',
    onb_q11_opt4: '🍓 Plump like a strawberry',
    onb_q11_opt5: '🍑 Soft like a peach',
    onb_q12_title: 'Where do you see fine lines when you look closely?',
    onb_q12_opt1: 'Around the eyes',
    onb_q12_opt2: 'Around the mouth',
    onb_q12_opt3: 'Forehead',
    onb_q12_opt4: 'All over the face',
    onb_q12_opt5: 'Nowhere',
    onb_q13_title: 'What is your main goal in skincare?',
    onb_q13_opt1: 'Reduce acne / breakouts',
    onb_q13_opt2: 'Fade dark spots',
    onb_q13_opt3: 'More glow and radiance',
    onb_q13_opt4: 'Anti‑aging care',
    onb_q13_opt5: 'Balance moisture',
    onb_q14_title: 'How would you describe your skin tone?',
    onb_q14_opt1: 'Very fair',
    onb_q14_opt2: 'Fair',
    onb_q14_opt3: 'Medium',
    onb_q14_opt4: 'Tan / olive',
    onb_q14_opt5: 'Deep / dark',
    onb_q15_title: 'Are you currently under dermatological treatment?',
    onb_q16_title: 'Do you use any prescription skincare products?',
    onb_q17_title: 'Are you pregnant or on hormonal treatment?',
    onb_q18_title: 'How much time can you spare for skincare?',
    onb_q18_opt1: 'Around 5 minutes',
    onb_q18_opt2: 'Around 10 minutes',
    onb_q18_opt3: '20 minutes or more',
    onb_q19_title: 'Do areas where you previously had acne look darker?',
    onb_q20_title: 'Do you have a lot of blackheads on your face?',
    onb_month_1: 'January',
    onb_month_2: 'February',
    onb_month_3: 'March',
    onb_month_4: 'April',
    onb_month_5: 'May',
    onb_month_6: 'June',
    onb_month_7: 'July',
    onb_month_8: 'August',
    onb_month_9: 'September',
    onb_month_10: 'October',
    onb_month_11: 'November',
    onb_month_12: 'December',
    onb_result_title: 'Your skin mini‑report is ready',
    onb_result_sub:
      'This summary is not a medical diagnosis; it simply helps us get to know your skin better so we can align future suggestions with your needs.',
    onb_result_skin_title: 'Your overall skin type 🌸',
    onb_result_skin_dry:
      'Your answers suggest that your skin tends to be dry. Gentle cleansers, barrier‑supporting moisturizers and consistent water intake will be especially important for you.',
    onb_result_skin_oily:
      'Your skin seems prone to oiliness. Foaming yet non‑stripping cleansers, lightweight moisturizers and regular sunscreen use can help keep things balanced.',
    onb_result_skin_combo:
      'You appear to have a combination skin type, with an oilier T‑zone and more balanced or dry cheeks. Using lighter textures on the T‑zone and richer formulas on the cheeks can work well for you.',
    onb_result_skin_normal:
      'Your skin looks relatively balanced overall. Sticking to gentle, barrier‑friendly products and daily sun protection can help you maintain this balance.',
    onb_result_hydration_title: 'Hydration & water balance 💧',
    onb_result_hydration_low:
      'Your water intake seems on the lower side. Sipping water regularly throughout the day can support both your overall health and your skin\'s moisture balance.',
    onb_result_hydration_mid:
      'Your water intake is not bad, but if you still feel dryness, it may help to review both the amount and how evenly it is spread throughout the day.',
    onb_result_hydration_good:
      'Your daily water intake looks good. Combining this with external hydration (serums and moisturizers) can give your skin a more plump and radiant look.',
    onb_result_sun_title: 'Sun protection ☀️',
    onb_result_sun_good:
      'Using sunscreen regularly is a great step for slowing visible aging and reducing the risk of dark spots. Keep up this habit as a non‑negotiable last step in your morning routine.',
    onb_result_sun_mid:
      'You use sunscreen sometimes, which is a good start. Making it a daily habit, especially as the final step of your morning routine, will protect your skin more effectively.',
    onb_result_sun_low:
      'You rarely or never use sunscreen. UV exposure can increase dark spots, fine lines and sensitivity; adding a daily SPF can make a big difference over time.',
    onb_result_focus_title: 'Main focus for your routine ✨',
    onb_result_focus_text_prefix: 'We will especially keep this goal in mind: ',
    onb_result_cta: 'Start the app',
    dailyRoutine: 'Daily Routine',
    morningRoutine: 'Morning Routine',
    eveningRoutine: 'Evening Routine',
    completedCount: 'completed',
    addTaskPlaceholder: 'Add new task...',
    addButton: 'Add',
    customTimeLabel: 'Custom',
    tapToSetTime: 'Tap to set time',
    setTime: 'Set time',
    skinAnalysis: 'Skin Analysis',
    cameraSubtitle: 'Take a photo of your skin or scalp and track your progress',
    takePhoto: 'Take Photo',
    selectFromGallery: 'Select from Gallery',
    analysisHistory: 'Analysis History',
    seeAll: 'See All',
    skinAnalysisType: 'Skin Analysis',
    scalpAnalysisType: 'Scalp Analysis',
    cameraPermissionTitle: 'Camera Permission',
    cameraPermissionMessage: 'We need camera access to take photos.',
    cameraPreview: 'Camera Preview',
    skinPhotoMode: 'Skin Photo',
    scalpMode: 'Scalp',
    skinTipsTitle: 'Skin Analysis Tips',
    skinTip1: 'Use natural light',
    skinTip2: 'Face the camera directly',
    skinTip3: 'Take photo without makeup',
    scalpTip1: 'Part hair clearly',
    scalpTip2: 'Keep scalp visible',
    scalpTip3: 'Use bright lighting',
    skinGuidance: 'Center your face in the frame',
    scalpGuidance: 'Center your hair parting in the frame',
    ok: 'OK',
    cancel: 'Cancel',
    later: 'Later',
    settings: 'Settings',
    searchUsersTopics: 'Search users or topics...',
    community: 'Community',
    comment: 'Comment',
    messages: 'Messages',
    createPost: 'Create Post',
    addPhoto: 'Add Photo',
    postPlaceholder: 'What do you want to share?',
    sendPost: 'Share',
    skinScore: 'Skin Score',
    scalpScore: 'Scalp Score',
    weekly: 'Weekly',
    monthly: 'Monthly',
    aiCommentImproved: 'Your skin barrier appears stronger since the last analysis.',
    aiCommentDecreased: 'Moisture level may have dropped. Consider reviewing your routine.',
    aiCommentStable: 'Your skin score is stable. You can continue your current routine.',
    analysisDetailTitle: 'Analysis Detail',
    typeMessage: 'Type a message...',
    send: 'Send',
    assistantWelcome: 'Hello! I\'m DermAI. Ask me anything about your skincare routine.',
    loginTab: 'Login',
    signUpTab: 'Sign Up',
    namePlaceholder: 'Name',
    surnamePlaceholder: 'Surname',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    confirmPasswordPlaceholder: 'Confirm password',
    forgotPassword: 'Forgot password?',
    loginButton: 'Login',
    signUpButton: 'Sign Up',
    appName: 'DermaGlow',
    resetPasswordTitle: 'Create New Password',
    resetPasswordSubtitle: 'Set a new password for your account.',
    newPasswordPlaceholder: 'New password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    updatePasswordButton: 'Update Password',
    resetPasswordSuccess: 'Your password has been updated. You can sign in now.',
    resetPasswordErrorShort: 'Password must be at least 6 characters.',
    resetPasswordErrorMismatch: 'Passwords do not match.',
    resetPasswordUseEmailLink: 'Use the password reset link from your email. When you open that link, you can set your new password here.',
    errorTitle: 'Error',
    successTitle: 'Success',
    fillAllFields: 'Please fill in all fields.',
    passwordsNotMatch: 'Passwords do not match.',
    enterEmailPassword: 'Please enter your email and password.',
    enterEmailFirst: 'Please enter your email address first to reset your password.',
    resetMailSent: 'Password reset link has been sent to your email.',
    accountCreated: 'Account created successfully. Let’s learn more about your skin.',

    // Premium UI
    welcomeTagline: 'Your personal skincare assistant',
    welcomeSubtitle: 'Discover your skin with AI analysis, custom routines, and community recommendations.',
    welcomeFooter: 'By continuing, you agree to our Terms of Use and Privacy Policy.',
    signInButton: 'Sign In',
    loginSubtitle: 'Sign in to your account',
    noAccountYet: "Don't have an account?",
    createAccountTitle: 'Create Account',
    createAccountSubtitle: 'Join the DermaGlow family',
    fullNamePlaceholder: 'Full Name',
    createAccountButton: 'Create Account',
    haveAccountAlready: 'Already have an account?',
    loginInstead: 'Sign In',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordSubtitle: 'We will send a password reset link to your email address.',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    welcomeBack: 'Welcome back',
    skinHealthScore: 'Skin Health Score',
    scalpHealthScore: 'Scalp Health Score',
    recommendedProducts: 'Recommended Products',
    communityHighlights: 'Community Highlights',
    quickActions: 'Quick Actions',
    dailyTips: 'Daily Tips',
    upcomingRoutine: 'Upcoming Routine Tasks',
    scalpAnalysis: 'Scalp Analysis',
    compatibility: 'Compatibility',
    rating: 'Rating',
    reviews: 'reviews',
    viewAll: 'View All',
    hydrationTracker: 'Daily Hydration',
    tabCommunity: 'Community',
    tabPremium: 'Premium',
    tabProfile: 'Profile',
    seeMore: 'Read more',
    emptyRoutine: 'No pending tasks for today',
    tipHydration: 'Drinking at least 2L of water daily supports skin elasticity.',
    tipSunscreen: 'Remember to use SPF 30+ sunscreen every day.',
    tipRoutine: 'Complete your evening routine 30 minutes before bed.',

    // Premium
    premiumBadge: 'DermaGlow Premium',
    premiumTitle: 'Upgrade to Premium',
    premiumSubtitle: 'Advanced AI analysis, exclusive product recommendations, and unlimited routine tracking.',
    currentPlan: 'Current Plan',
    freePlan: 'Free',
    active: 'Active',
    premiumFeaturesTitle: 'Premium Features',
    premiumFeature1: 'Unlimited skin and scalp AI analysis',
    premiumFeature2: 'Detailed score reports and trend charts',
    premiumFeature3: 'Personalized AI care assistant',
    premiumFeature4: 'Exclusive product picks and community access',
    premiumFeature5: 'Priority customer support',
    premiumFeature6: 'Ad-free experience',
    premiumPlansTitle: 'Plans',
    premiumPlanMonthly: 'Monthly Plan',
    premiumPlanYearly: 'Yearly Plan',
    premiumPriceMonthly: '$9.99 / mo',
    premiumPriceYearly: '$59.99 / yr',
    premiumYearlySaving: 'Save 44%',
    mostPopular: 'Most Popular',
    upgradeNow: 'Upgrade to Premium',
    premiumDisclaimer: 'Subscription renews automatically. Cancel anytime.',

    // --- SUPABASE VERİTABANI HATALARI İÇİN İNGİLİZCE ÇEVİRİLER ---
    authErrorInvalidCredentials: 'Invalid login credentials. Please check your email and password.',
    authErrorAlreadyRegistered: 'This email is already registered.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}